# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7efce1559c2540ab6411319d616d1b2e032120064e27edd6d462d64e6e7efa956ad5bc6c061a470dd64705b60cba577763ea78f846e99bb4db9007f9fbe1ff30

test:
  secret_key_base: 7d1bbc6f63bde118fe8453cdf17ebf29de7d730021f3710671fb09da00e1100c3aff18cb1aa5d64ab07ac8ec15217b67a8ff044114f6e407af19c17a7d9d5440

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
